# Generated by Django 4.1.2 on 2022-10-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0002_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lyric",
            fields=[
                ("content", models.TextField()),
                ("song_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
