# Generated by Django 4.1.2 on 2022-10-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0004_rename_song_id_lyric_id_rename_artiste_id_song_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lyric",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
