# Generated by Django 4.1.2 on 2022-10-29 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0006_remove_song_artiste_remove_song_id_song_artiste_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song", old_name="artiste_id", new_name="id",
        ),
        migrations.AddField(
            model_name="song",
            name="artiste",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="musicapp.artiste",
            ),
        ),
        migrations.AlterField(
            model_name="lyric",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
